### ISSUE TITLE
What about the Phalastinians? Iraqis? Gaza? Barma?

### ISSUE THREAD

**Issue by ZeroCoolHacker** [erkexzcx/stoppropaganda#116] opened 2022-03-07 06:07 UTC
Double standards

**Comment by erkexzcx** [comment] 2022-03-07 07:13
Here is my opinion:
- They don't have their military in Ukraine.
- They are not directly communicating with putin (in comparison to belarus)
- They are not targets in IT Army of Ukraine telegram group.
- Root cause remains russia (and it's puppet belarus).

So I don't really see the point of adding them. It's already 300+ websites and with each release the impact on a single website is being reduced as load is being split to each website. :)

**Comment by cpueasy** [comment] 2022-03-07 12:43
Ukrainian Terrorist ruled government and it's puppet zelensky you mean?

**Comment by stinkfoot** [comment] 2022-03-07 15:40
> Double standards

In the upper right corner of your Github dashboard, you can find the "Fork" button.  This will allow you to modify your own version of the source code as you see fit.

**Comment by kremalicious** [comment] 2022-03-07 18:19
> Double standards

[Whataboutism](https://en.wikipedia.org/wiki/Whataboutism) does not help towards the clearly scoped goal of this repo in any way. Targeting further information networks of enemies of liberty and free speech, like Hamas, Hezbollah, Taliban, or Tatmadaw is admirable but out of scope of this project. As mentioned before, the fork button is your friend.

**Comment by Toxyl** [comment] 2022-03-07 18:58
Who are the **Phala**stinians, anyway?

**Closed** 2022-03-07 20:28 UTC

**Comment by kremalicious** [comment] 2022-03-07 23:18
> Who are the Phalastinians, anyway?

Actually sounds like a cool culture shared between Palestinians and Phoenicians, but although the place sort of matches, it's like 2500 years too late for that.
